### PR TITLE
Fix getting IPv6 address command

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by C3n7ral051nt4g3ncy** [comment]
Hi @PeterDaveHello , thanks for your PR.
This isn't a fix my end, its the opposite.

- ` curl -4 icanhazip.com` works perfectly.

- `curl -6 icanhazip.com` does not.

see below:

**Comment by PeterDaveHello** [comment]
@C3n7ral051nt4g3ncy `-4` shouldn't and won't give use IPv6, maybe you can use `-v` and make sure IPv6 is available when testing? What about https://ipv6.ipinfo.tw, can you reach it?

**Comment by C3n7ral051nt4g3ncy** [comment]
@PeterDaveHello : this one :  `curl https://api64.ipify.org`

**Comment by C3n7ral051nt4g3ncy** [comment]
Do you get a results using `curl -6 icanhazip.com`?

**Comment by PeterDaveHello** [comment]
> Do you get a results using `curl -6 icanhazip.com`?

I can get result from it 👍

**Comment by C3n7ral051nt4g3ncy** [comment]
Perfect ! Thanks for your PR @PeterDaveHello , **it has been merged.**

**Pull request merged**
